services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: Yazan6879

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080